# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 23 Apr 2014 02:46:24 +0000
*               @ALL          1
*               @user         8
