<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: e
 * Date: Tue, 15 Sep 2015 23:13:11 -0700
 */

$conf['title'] = '百度产品部门 知识库';
$conf['lang'] = 'zh';
$conf['template'] = 'vector';
$conf['license'] = '';
$conf['recent_days'] = 30;
$conf['youarehere'] = 1;
$conf['showuseras'] = 'username';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['subscribers'] = 1;
$conf['registernotify'] = '01@eexx.me';
$conf['proxy']['user'] = 'e';
$conf['proxy']['pass'] = '<b>NDQ0NDMzMw==';
$conf['plugin']['include']['showpermalink'] = 1;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showmdate'] = 1;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showeditbtn'] = 0;
$conf['plugin']['markdownextra']['frontmatter'] = 1;

// end auto-generated content
